# Generated by Django 3.0.2 on 2021-07-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20210728_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Clivk link above to read post', max_length=255),
        ),
    ]
